name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Créer fichier .env 
        run: | 
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env 
          echo "DB_NAME=labo02_db" >> .env
          echo "DB_USER=labo02" >> .env 
          echo "DB_PASS=lab02" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env 
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Exécuter les tests
        run: |
          export PYTHONPATH=src  # ajoute src au path pour que Python trouve calculator.py
          python -m pytest
          
  deploy:
    runs-on: self-hosted
    needs: test   # Ne se lance que si les tests passent
    steps:
      - uses: actions/checkout@v4

      - name: Déploiement local
        run: |
          cd $GITHUB_WORKSPACE
          echo "Déploiement sur la VM en cours..."

          docker compose down || true
          docker compose up -d --build

